name: Test Build

on:
  push:
    branches:
      - master
      - v0.2
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            RUNNER_OS: linux
          - os: macos-10.15
            RUNNER_OS: darwin
          - os: windows-2019
            RUNNER_OS: windows
        goarch: [amd64, arm64]
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - run: make build
        env:
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ github.ref_name }}